name: build

on:
  push:
    branches:
      - '**'

permissions:
  actions: read
  contents: read

jobs:
  build:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-build-test.yml@203116543badcfcd7abcca662aced7ffcaf438d4 # 0.55.4
    with:
      install-node: true
      build-commands: |
        npm ci
        npm run build
      test-commands: npm test