name: create-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

permissions:
  actions: read
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-release-nodejs.yml@203116543badcfcd7abcca662aced7ffcaf438d4 # 0.55.4
    with:
      version: ${{ github.event.inputs.version }}
      build-commands: |
        npm ci
        npm run package
        npm test
      artifact-path: dist/
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      pat: ${{ secrets.REPO_ACCESS }}
      npm-token: ${{ secrets.NPM_TOKEN }}